@extends('layouts.app')
@section('title', 'Terms of Service — Yatri')
@section('meta_description', 'Yatri terms of service — rules and guidelines for using the AI trip planning platform.')

@section('content')
<div class="wrap" style="padding-top:48px;padding-bottom:100px;max-width:720px">
  <p class="eyebrow">Legal</p>
  <h1 style="margin:0 0 24px"><strong>Terms of Service</strong></h1>

  <div style="color:var(--md-on-surface-variant);font-size:15px;line-height:1.7;display:flex;flex-direction:column;gap:20px">
    <p><em>Last updated: June 2026</em></p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>1. Acceptance of Terms</strong></h2>
    <p>By using Yatri, you agree to these Terms of Service. If you do not agree, do not use the service.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>2. Description of Service</strong></h2>
    <p>Yatri is an AI-powered trip planning platform. It generates suggested itineraries using artificial intelligence and live data from third-party services. Itineraries are <strong>suggestions only</strong> and should be verified independently.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>3. User Accounts</strong></h2>
    <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account. You must be at least 13 years old to use Yatri.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>4. Acceptable Use</strong></h2>
    <p>You agree not to:</p>
    <ul style="padding-left:20px">
      <li>Use the service for any unlawful purpose.</li>
      <li>Generate itineraries for harmful, fraudulent, or deceptive purposes.</li>
      <li>Attempt to reverse-engineer, scrape, or abuse the AI generation system.</li>
      <li>Post content that is harassing, abusive, or violates others' rights.</li>
    </ul>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>5. AI-Generated Content</strong></h2>
    <p>Itineraries are generated by AI and may contain inaccuracies. Always verify prices, opening hours, availability, and travel requirements independently. Yatri is not responsible for losses incurred from relying on AI-generated suggestions.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>6. Limitation of Liability</strong></h2>
    <p>Yatri is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>7. Changes to Terms</strong></h2>
    <p>We may update these terms at any time. Continued use after changes constitutes acceptance of the new terms.</p>

    <h2 style="margin:0;color:var(--md-on-surface)"><strong>8. Contact</strong></h2>
    <p>Questions about these terms? <a href="{{ route('contact') }}" style="color:var(--md-primary)">Contact us</a>.</p>
  </div>
</div>
@endsection
